Added a sudoloop to prevent auth timeout
Using sudo verification, create a sudo loop to prevent timeout. This will prevent
issues where after a long download, user leaves machine and returns to a failed update,
forcing one to do the entire update all over again. This can occur with slow networks or
a large amount of hosts data.

Also set certain important vars to read only, to prevent their modification during runtime.

One important note is that like the check for sudo, the sudo loop will only be active if the
user is not effective root.

diff --git a/update-hosts b/update-hosts
--- a/update-hosts
+++ b/update-hosts
@@ -12,19 +12,20 @@ set -eu
 set -o pipefail
 
 # Configuration:
+readonly sudolock="/tmp/update-hosts.sudolock"
 blocklist="" # Leave this blank
 hosts="" # Leave this blank
-dst_hosts="/etc/hosts"
-dst_backup="${dst_hosts}.backup.$(date +%Y%m%d)"
-dst_ip="0.0.0.0"
+readonly dst_hosts="/etc/hosts"
+readonly dst_backup="${dst_hosts}.backup.$(date +%Y%m%d)"
+readonly dst_ip="0.0.0.0"
 # NOTE: Adding the alias of the 0 domain to itself fixes a display issue that
 #       can occur when using traceroute, netstat and the like.
-header="
+readonly header="
 127.0.0.1 $(uname -n) localhost
 255.255.255.255 broadcasthost
 0.0.0.0 0.0.0.0
 "
-sources=(
+readonly sources=(
 	"http://winhelp2002.mvps.org/hosts.txt"
 	"http://someonewhocares.org/hosts/hosts"
 	"http://hosts-file.net/ad_servers.txt" # Ad servers only
@@ -36,7 +37,7 @@ sources=(
 	"http://malwaredomains.lehigh.edu/files/justdomains"
 )
 
-whitelist=(
+readonly whitelist=(
 	# DO NOT REMOVE, WHITELIST must always contain an entry
 	# I use example.com as it will always route to an example webpage
 	"example.com"
@@ -48,7 +49,7 @@ whitelist=(
 # BLACKLIST DOMAINS
 #    agor.io: Jumpscare
 #    pinion.gg: Ads in Counter Strike: Global Offensive and other games
-blacklist=(
+readonly blacklist=(
 	"agor.io"
 	"www.agor.io"
 	"adback.pinion.gg"
@@ -96,21 +97,21 @@ blacklist=(
 ##
 # Display a general message
 ##
-action_msg() {
+function action_msg() {
 	printf "%b + %b%s%b\n" "\e[1;33m" "\e[1;32m" "$1" "\e[0m"
 }
 
 ##
 # Display an information snippet
 ##
-info_msg() {
+function info_msg() {
 	printf "   - %s\n" "$1"
 }
 
 ##
 # Check the environment path for the either wget or curl, exit if it is not found
 ##
-check_for_download_ability() {
+function check_for_download_ability() {
 	if ! which curl > /dev/null 2>&1; then
 		if ! which wget > /dev/null 2>&1; then
 			printf "Either wget or curl are required for operation of this script\n"
@@ -123,7 +124,7 @@ check_for_download_ability() {
 ##
 # Check the environment path for the given binary, exit if it is not found
 ##
-check_for_binary() {
+function check_for_binary() {
 	if ! which "$1" > /dev/null 2>&1; then
 		printf "The '%s' binary is required for operation of this script.\n" "$1"
 		printf "Please install '%s' onto your system.\n" "$1"
@@ -134,7 +135,7 @@ check_for_binary() {
 ##
 # Print out the user configuration
 ##
-print_config() {
+function print_config() {
 	info_msg "Hosts location: ${dst_hosts}"
 	info_msg "Destination IP: ${dst_ip}"
 }
@@ -142,7 +143,7 @@ print_config() {
 ##
 # Sources list parsing
 ##
-download_sources() {
+function download_sources() {
 	# Check for curl, if not found, use wget, as the check for either
 	# Should have passed before this function
 	if which curl > /dev/null 2>&1; then
@@ -172,7 +173,7 @@ download_sources() {
 ##
 # Change EOL from DOS to Unix format
 ##
-change_eol() {
+function change_eol() {
 	info_msg "Change EOL to Unix format"
 	blocklist=$(printf "%s\n" "${blocklist}" | sed 's/$//')
 }
@@ -180,7 +181,7 @@ change_eol() {
 ##
 # Only select lines which contain a host, do not select comments/other
 ##
-select_host_lines() {
+function select_host_lines() {
 	info_msg "Select only hosts lines"
 	local ip_regex='([0-9]{1,3}\.){3}[0-9]{1,3}[[:blank:]]+'
 	local domain_regex='([[:alnum:]_-]{1,63}\.)+[[:alpha:]][[:alnum:]_-]{1,62}'
@@ -192,7 +193,7 @@ select_host_lines() {
 ##
 # Remove any predefined destinations, as they may be untrustworthy
 ##
-remove_untrusted_domain() {
+function remove_untrusted_domain() {
 	info_msg "Remove old destination"
 	blocklist=$(printf "%s\n" "${blocklist}" | sed -r 's/^([0-9]{1,3}\.){3}[0-9]{1,3}[[:space:]]+//g')
 }
@@ -200,7 +201,7 @@ remove_untrusted_domain() {
 ##
 # Normalize all entries to lowercase strings
 ##
-normalize_to_lowercase() {
+function normalize_to_lowercase() {
 	info_msg 'Transform all entries to lowercase'
 	blocklist=$(printf "%s\n" "${blocklist}" | awk '{print tolower($0)}')
 }
@@ -208,7 +209,7 @@ normalize_to_lowercase() {
 ##
 # Remove any entries containing the localhost, as it will be added by the header later on
 ##
-remove_local_entries() {
+function remove_local_entries() {
 	info_msg "Remove local entries"
 	blocklist=$(printf "%s\n" "${blocklist}" | grep -Ev '^(localhost|localhost.localdomain|local|broadcasthost)$')
 }
@@ -216,7 +217,7 @@ remove_local_entries() {
 ##
 # Apply the user whitelist
 ##
-apply_whitelist() {
+function apply_whitelist() {
 	info_msg "Apply whitelist"
 	for domain in "${whitelist[@]}"; do
 		blocklist=$(printf "%s\n" "${blocklist}" | grep -Fxv "${domain}")
@@ -226,7 +227,7 @@ apply_whitelist() {
 ##
 # Apply the user blacklist
 ##
-apply_blacklist() {
+function apply_blacklist() {
 	info_msg "Apply blacklist"
 	# Cache the blacklist domains so that the entire block list
 	# does not have to be echoed each time.
@@ -249,7 +250,7 @@ apply_blacklist() {
 ##
 # Remove duplicate entries
 ##
-remove_duplicates() {
+function remove_duplicates() {
 	info_msg "Remove duplicate entries"
 	blocklist=$(printf "%s\n" "${blocklist}" | awk '!a[$0]++')
 }
@@ -257,7 +258,7 @@ remove_duplicates() {
 ##
 # Sort the entries by string numerical value
 ##
-sort_entries() {
+function sort_entries() {
 	info_msg "Sort entries"
 	blocklist=$(printf "%s\n" "${blocklist}" | sort -n)
 }
@@ -265,7 +266,7 @@ sort_entries() {
 ##
 # Add the configured destination, by default the zero address
 ##
-add_new_destination() {
+function add_new_destination() {
 	info_msg "Add new destination"
 	blocklist=$(printf "%s\n" "${blocklist}" | sed "s/^/${dst_ip} /g")
 }
@@ -273,7 +274,7 @@ add_new_destination() {
 ##
 # Parse the header and create the new hosts file
 ##
-generate_new_hosts_file() {
+function generate_new_hosts_file() {
 	header=$(printf "# <header>%s# </header>\n" "${header}")
 	header=$(printf "# %s\n%s\n" "$(date)" "${header}")
 	hosts=$(printf "%s\n# <blocklist>\n%s\n# </blocklist>" "${header}" "${blocklist}")
@@ -282,7 +283,7 @@ generate_new_hosts_file() {
 ##
 # Backup original hosts file
 ##
-backup_old_hosts_file() {
+function backup_old_hosts_file() {
 	info_msg "Creating backup of original hosts file..."
 	if [ "${EUID}" -ne 0 ]; then
 		sudo cp "${dst_hosts}" "${dst_backup}"
@@ -294,7 +295,7 @@ backup_old_hosts_file() {
 ##
 # Install the new hosts file to the destination
 ##
-install_new_hosts_file() {
+function install_new_hosts_file() {
 	info_msg "Installing new hosts file..."
 	if [ "${EUID}" -ne 0 ]; then
 		printf "%s\n" "${hosts}" | sudo tee "${dst_hosts}" > /dev/null
@@ -306,7 +307,7 @@ install_new_hosts_file() {
 ##
 # Fixes permission on file to 644
 ##
-fix_file_permissons() {
+function fix_file_permissons() {
 	info_msg "Fixing permissions for file $1..."
 	if [ "${EUID}" -ne 0 ]; then
 		sudo chmod 644 "$1"
@@ -318,7 +319,7 @@ fix_file_permissons() {
 ##
 # Print the differences between the number of hosts in each file
 ##
-print_hosts_file_differences() {
+function print_hosts_file_differences() {
 	local old_hosts_number=$(wc -l < ${dst_backup})
 	local new_hosts_number=$(wc -l < ${dst_hosts})
 	printf "%b + %b%s %bhosts added! (%b + %b%s %b)\n" \
@@ -328,23 +329,52 @@ print_hosts_file_differences() {
 	unset old_hosts_number new_hosts_number
 }
 
+function sudoloop()
+{
+        touch "${sudolock}"
+        while [[ -e "${sudolock}" ]]; do
+                sudo -n -v
+                sleep 2
+        done
+}
+
+function cancel_sudoloop()
+{
+        [[ -e "${sudolock}" ]] && rm -f "${sudolock}"
+        exit 0
+}
+
 
 # Script begins here
 
 # Check for required binaries, exit out if they are not present
 check_for_download_ability
-if [ "${EUID}" -ne 0 ]; then
-        check_for_binary sudo
-fi
 check_for_binary sed
 check_for_binary grep
 check_for_binary sort
+check_for_binary touch
+check_for_binary sleep
+check_for_binary rm
 check_for_binary awk
 check_for_binary tee
 check_for_binary cp
 check_for_binary wc
 check_for_binary printf
 check_for_binary chmod
+
+if [[ "${EUID}" -ne 0 ]]; then
+        check_for_binary sudo
+
+        # initialize sudo
+        sudo -v || exit 1
+
+        # Start sudoloop
+        sudoloop &
+
+        # Trap exit signals
+        trap cancel_sudoloop INT
+fi
+
 
 # Process begins:
 action_msg "Configuration:"
@@ -373,3 +403,5 @@ fix_file_permissons "${dst_hosts}"
 fix_file_permissons "${dst_backup}"
 print_hosts_file_differences
 
+# Cleanup
+cancel_sudoloop
