Formatting with heredocs

diff --git a/update-hosts b/update-hosts
--- a/update-hosts
+++ b/update-hosts
@@ -450,8 +450,12 @@ print_ipset_config()
 
   # The ipset must exist first for this script to work
   # check for existence here
-  ${print_ipset_config__sudo} ipset list "${print_ipset_config__name}" > /dev/null 2>&1 || {
-    error_msg "The ipset: ${print_ipset_config__name} must exist before running this script."
+  ${print_ipset_config__sudo} ipset \
+    list "${print_ipset_config__name}" > /dev/null 2>&1 || {
+    error_msg "$(cat << EOF
+The ipset: ${print_ipset_config__name} must exist before running this script.
+EOF
+)"
     error_msg "Create it using: # ipset create ${print_ipset_config__name}"
 
     unset print_ipset_config__sudo
@@ -479,7 +483,10 @@ decide_dl_client()
   decide_dl_client__cmd=
 
   if which curl > /dev/null 2>&1; then
-    decide_dl_client__cmd="curl -fsSL --connect-timeout 40 --max-time 60 -A 'Mozilla/5.0'"
+    decide_dl_client__cmd="$(cat << EOF
+curl -fsSL --connect-timeout 40 --max-time 60 -A 'Mozilla/5.0'
+EOF
+)"
   else
     decide_dl_client__cmd="wget -T 10 -qO- -A 'Mozilla/5.0'"
   fi
@@ -502,8 +509,10 @@ process_ipset_sources()
   process_ipset_sources__file="$1"
   process_ipset_sources__url="$2"
 
-  change_eol "${process_ipset_sources__file}" "${process_ipset_sources__url}"
-  select_ip_lines "${process_ipset_sources__file}" "${process_ipset_sources__url}"
+  change_eol "${process_ipset_sources__file}" \
+    "${process_ipset_sources__url}"
+  select_ip_lines "${process_ipset_sources__file}" \
+    "${process_ipset_sources__url}"
 
   unset process_ipset_sources__file
   unset process_ipset_sources__url
@@ -521,11 +530,16 @@ process_hosts_sources()
   process_hosts_sources__file="$1"
   process_hosts_sources__url="$2"
 
-  change_eol "${process_hosts_sources__file}" "${process_hosts_sources__url}"
-  select_host_lines "${process_hosts_sources__file}" "${process_hosts_sources__url}"
-  remove_untrusted_domain "${process_hosts_sources__file}" "${process_hosts_sources__url}"
-  normalize_to_lowercase "${process_hosts_sources__file}" "${process_hosts_sources__url}"
-  remove_local_entries "${process_hosts_sources__file}" "${process_hosts_sources__url}"
+  change_eol "${process_hosts_sources__file}" \
+    "${process_hosts_sources__url}"
+  select_host_lines "${process_hosts_sources__file}" \
+    "${process_hosts_sources__url}"
+  remove_untrusted_domain "${process_hosts_sources__file}" \
+    "${process_hosts_sources__url}"
+  normalize_to_lowercase "${process_hosts_sources__file}" \
+    "${process_hosts_sources__url}"
+  remove_local_entries "${process_hosts_sources__file}" \
+    "${process_hosts_sources__url}"
 
   unset process_hosts_sources__file
   unset process_hosts_sources__url
@@ -549,17 +563,20 @@ download_to_tempfile()
   download_to_tempfile__content=
 
   info_msg "Downloading from ${download_to_tempfile__url}"
-  download_to_tempfile__content="$(printf -- "%s" "$(${download_to_tempfile__client} "${download_to_tempfile__url}")")"
+  download_to_tempfile__content="$(printf -- "%s" \
+    "$(${download_to_tempfile__client} "${download_to_tempfile__url}")")"
   if [ -z "${download_to_tempfile__content}" ]; then
     info_msg "  Failed to download from: ${download_to_tempfile__url}"
     return 1
   fi
 
   # Guarantee an empty file
-  printf -- "%s\n" "${download_to_tempfile__content}" > "${download_to_tempfile__file}"
+  printf -- "%s\n" "${download_to_tempfile__content}" \
+    > "${download_to_tempfile__file}"
 
   # Run after download processing hook
-  "${download_to_tempfile__process_hook}" "${download_to_tempfile__file}" "${download_to_tempfile__url}"
+  "${download_to_tempfile__process_hook}" \
+    "${download_to_tempfile__file}" "${download_to_tempfile__url}"
 
   unset download_to_tempfile__client
   unset download_to_tempfile__process_hook
@@ -591,7 +608,9 @@ download_sources()
     # Add the tempfile to list of temporary files
     __temp_files="${download_sources__tempfile} "${__temp_files}
 
-    download_to_tempfile "${download_sources__client}" "${download_sources__url}" "${download_sources__tempfile}" "${download_sources__process_hook}" &
+    download_to_tempfile "${download_sources__client}" \
+      "${download_sources__url}" "${download_sources__tempfile}" \
+      "${download_sources__process_hook}" &
 
     # Add the pid to list of pids
     __pids="${__pids} $!"
@@ -648,7 +667,10 @@ change_eol()
 {
   change_eol__file="$1"
   change_eol__url="$2"
-  info_msg "Change EOL to Unix format: ${change_eol__url} (${change_eol__file})"
+  info_msg "$(cat << EOF
+Change EOL to Unix format: ${change_eol__url} (${change_eol__file})
+EOF
+)"
   sed -r -i 's/$//' "${change_eol__file}"
 
   unset change_eol__file
@@ -673,7 +695,11 @@ select_host_lines()
   # sed -n -i -r "/(^(${ip_regex})|^)${domain_regex}/p" "$1"
   #
   # This is an ugly workaround
-  info_msg "Select only hosts lines: ${select_host_lines__url} (${select_host_lines__file})"
+  info_msg "$(cat << EOF
+Select only hosts lines: ${select_host_lines__url} \
+(${select_host_lines__file})
+EOF
+)"
 
   select_host_lines__content=
   select_host_lines__content="$(grep -oE \
@@ -700,7 +726,10 @@ select_ip_lines()
   select_ip_lines__file="$1"
   select_ip_lines__url="$2"
 
-  info_msg "Select only IP lines: ${select_ip_lines__url} (${select_ip_lines__file})"
+  info_msg "$(cat << EOF
+Select only IP lines: ${select_ip_lines__url} (${select_ip_lines__file})
+EOF
+)"
   select_ip_lines__content=
   select_ip_lines__content="$(grep -oE "${REGEX_SELECT_IP_ADDRESS}" \
     "${select_ip_lines__file}")"
@@ -724,8 +753,13 @@ remove_untrusted_domain()
 {
   remove_untrusted_domain__file="$1"
   remove_untrusted_domain__url="$2"
-  info_msg "Remove old destination: ${remove_untrusted_domain__url} (${remove_untrusted_domain__file})"
-  sed -i -r 's/^([0-9]{1,3}\.){3}[0-9]{1,3}[[:space:]]+//g' "${remove_untrusted_domain__file}"
+  info_msg "$(cat << EOF
+Remove old destination: ${remove_untrusted_domain__url} \
+(${remove_untrusted_domain__file})
+EOF
+)"
+  sed -i -r 's/^([0-9]{1,3}\.){3}[0-9]{1,3}[[:space:]]+//g' \
+    "${remove_untrusted_domain__file}"
 
   unset remove_untrusted_domain__file
   unset remove_untrusted_domain__url
@@ -747,11 +781,17 @@ normalize_to_lowercase()
   # awk -v tf="$1" '{print tolower($0) > tf}' "$1"
   #
   # This is an ugly work around
-  info_msg "Transform all entries to lowercase: ${normalize_to_lowercase__url} (${normalize_to_lowercase__file})"
+  info_msg "$(cat << EOF
+Transform all entries to lowercase: ${normalize_to_lowercase__url} \
+(${normalize_to_lowercase__file})
+EOF
+)"
 
   normalize_to_lowercase__content=
-  normalize_to_lowercase__content="$(awk '{print tolower($0)}' "${normalize_to_lowercase__file}")"
-  printf -- "${normalize_to_lowercase__content}" > "${normalize_to_lowercase__file}"
+  normalize_to_lowercase__content="$(awk '{print tolower($0)}' \
+    "${normalize_to_lowercase__file}")"
+  printf -- "${normalize_to_lowercase__content}" \
+    > "${normalize_to_lowercase__file}"
 
   unset normalize_to_lowercase__file
   unset normalize_to_lowercase__url
@@ -771,7 +811,11 @@ remove_local_entries()
   remove_local_entries__file="$1"
   remove_local_entries__url="$2"
 
-  info_msg "Remove local entries: ${remove_local_entries__url} (${remove_local_entries__file})"
+  info_msg "$(cat << EOF
+Remove local entries: ${remove_local_entries__url} \
+(${remove_local_entries__file})
+EOF
+)"
   sed -n -i -r '/^(localhost|localhost.localdomain|local|broadcasthost)$/!p' \
     "${remove_local_entries__file}"
 
@@ -796,7 +840,8 @@ apply_whitelist()
   fi
 
   for apply_whitelist__domain in ${apply_whitelist__whitelist}; do
-    __blocklist="$(printf -- "%s\n" "${__blocklist}" | sed -r "/${apply_whitelist__domain}/d")"
+    __blocklist="$(printf -- "%s\n" "${__blocklist}" \
+      | sed -r "/${apply_whitelist__domain}/d")"
     unset apply_whitelist__domain
   done
 
@@ -832,7 +877,8 @@ apply_blacklist()
   if [ -z "${__blocklist}" ]; then
     __blocklist="$(printf -- "%s\n" "${apply_blacklist__domains}")"
   else
-    __blocklist="$(printf -- "%s\n%s\n" "${__blocklist}" "${apply_blacklist__domains}")"
+    __blocklist="$(printf -- "%s\n%s\n" \
+      "${__blocklist}" "${apply_blacklist__domains}")"
   fi
 
   unset apply_blacklist__domains
@@ -889,7 +935,8 @@ generate_new_hosts_file()
   generate_new_hosts_file__header=
 
   info_msg "Create new hosts file"
-  generate_new_hosts_file__header="$(printf -- "# <hosts_header>%s# </hosts_header>\n" "${HOSTS_HEADER}")"
+  generate_new_hosts_file__header="$(printf -- \
+    "# <hosts_header>%s# </hosts_header>\n" "${HOSTS_HEADER}")"
   generate_new_hosts_file__header="$(printf -- "# %s\n%s\n" \
     "$(date)" \
     "${generate_new_hosts_file__header}")"
@@ -918,7 +965,8 @@ backup_old_file()
 
   if [ -f "${backup_old_file__file}" ]; then
     info_msg "Creating backup of original file..."
-    ${backup_old_file__sudo} cp "${backup_old_file__file}" "${backup_old_file__backup}" || {
+    ${backup_old_file__sudo} cp \
+      "${backup_old_file__file}" "${backup_old_file__backup}" || {
       error_msg "Failed to copy to file ${backup_old_file__backup}"
 
       unset backup_old_file__sudo
@@ -951,7 +999,8 @@ install_new_hosts_file()
 
   info_msg "Installing new hosts file..."
   printf -- "%s\n" "${install_new_hosts_file__hosts}" \
-    | ${install_new_hosts_file__sudo} tee "${install_new_hosts_file__destination}" > /dev/null \
+    | ${install_new_hosts_file__sudo} tee \
+    "${install_new_hosts_file__destination}" > /dev/null \
     || {
     error_msg "Failed to output to file ${install_new_hosts_file__destination}"
 
@@ -983,18 +1032,23 @@ install_ipset_blocklist()
   action_msg "Install the ipset blocklist"
   info_msg "Clear existing block list"
   printf -- "" \
-    | ${install_ipset_blocklist__sudo} tee "${install_ipset_blocklist__file}" > /dev/null
-  ${install_ipset_blocklist__sudo} ipset flush "${install_ipset_blocklist__name}"
+    | ${install_ipset_blocklist__sudo} \
+    tee "${install_ipset_blocklist__file}" > /dev/null
+  ${install_ipset_blocklist__sudo} ipset \
+    flush "${install_ipset_blocklist__name}"
 
   info_msg "Create new blocklist"
   # Save here just to get the create line
   ${install_ipset_blocklist__sudo} ipset save \
-    "${install_ipset_blocklist__name}" -file "${install_ipset_blocklist__file}"
+    "${install_ipset_blocklist__name}" \
+    -file "${install_ipset_blocklist__file}"
 
   info_msg "Add new IPs to the block list"
-  __blocklist=$(printf -- "%s\n" "${__blocklist}" | sed -e 's/^/add blocklist /')
+  __blocklist=$(printf -- "%s\n" "${__blocklist}" \
+    | sed -e 's/^/add blocklist /')
   printf -- "%s\n" "${__blocklist}" \
-    | ${install_ipset_blocklist__sudo} tee -a "${install_ipset_blocklist__file}" > /dev/null \
+    | ${install_ipset_blocklist__sudo} tee \
+    -a "${install_ipset_blocklist__file}" > /dev/null \
     || {
     error_msg "Failed to add ipset to blocklist"
 
@@ -1005,7 +1059,8 @@ install_ipset_blocklist()
   }
 
   info_msg "Commit new ipset"
-  ${install_ipset_blocklist__sudo} ipset restore -exist -file "${install_ipset_blocklist__file}"
+  ${install_ipset_blocklist__sudo} ipset restore \
+    -exist -file "${install_ipset_blocklist__file}"
 
   unset install_ipset_blocklist__sudo
   unset install_ipset_blocklist__file
@@ -1036,7 +1091,10 @@ fix_file_permissons()
       return 1
     }
   else
-    info_msg "Cannot fix permission for non-existant file ${fix_file_permissons__file}"
+    info_msg "$(cat << EOF
+Cannot fix permission for non-existant file ${fix_file_permissons__file}
+EOF
+)"
   fi
 
   unset fix_file_permissons__sudo
@@ -1071,17 +1129,20 @@ print_file_differences()
 
   print_file_differences__old_number=0
   if [ -f "${print_file_differences__old}" ]; then
-    print_file_differences__old_number=$(wc -l < "${print_file_differences__old}")
+    print_file_differences__old_number=$(wc -l \
+      < "${print_file_differences__old}")
   fi
 
   print_file_differences__new_number=
-  print_file_differences__new_number=$(wc -l < "${print_file_differences__new}")
+  print_file_differences__new_number=$(wc -l \
+    < "${print_file_differences__new}")
 
   # Echo out the result
   printf -- "%b + %b%s %bentries added! (%b + %b%s %b)\n" \
     "\033[1;33m" "\033[1;32m" "${print_file_differences__new_number}" \
     "\033[0m" "\033[1;32m" "\033[1;34m" \
-    "$((print_file_differences__new_number - print_file_differences__old_number))" \
+    "$((print_file_differences__new_number \
+    - print_file_differences__old_number))" \
     "\033[0m"
 
   unset print_file_differences__old
@@ -1100,9 +1161,11 @@ remove_all_backup_files()
 {
   remove_all_backup_files__sudo="$1"
   remove_all_backup_files__file="$2"
-  for remove_all_backup_files__temp in "${remove_all_backup_files__file}".backup.*; do
+  for remove_all_backup_files__temp in \
+    "${remove_all_backup_files__file}".backup.*; do
     info_msg "Removing backup file: ${remove_all_backup_files__temp}..."
-    ${remove_all_backup_files__sudo} rm -f "${remove_all_backup_files__temp}" > /dev/null 2>&1
+    ${remove_all_backup_files__sudo} rm -f \
+      "${remove_all_backup_files__temp}" > /dev/null 2>&1
     unset remove_all_backup_files__temp
   done
 
@@ -1153,7 +1216,8 @@ cleanup()
 }
 
 ##
-# Cancels the sudoloop if it is running, performs cleanup and then exits the script
+# Cancels the sudoloop if it is running
+# performs cleanup and then exits the script
 cancel_sudoloop()
 {
   [ -e "${SUDOLOCK}" ] && rm -f "${SUDOLOCK}"
@@ -1178,16 +1242,19 @@ print_version()
 print_help()
 {
   print_version
-  printf -- "  Options:\n"
-  printf -- "     -h | --help     Display help\n"
-  printf -- "     -v | --version  Display version\n"
-  printf -- "     -r | --remove   Remove backups\n"
-  printf -- "     -n | --noroot   Do not require root to output\n"
-  printf -- "     -i | --ipset    Also download ipset sources\n"
-  printf -- "     --output-hosts  The file to output hosts to\n"
-  printf -- "     --output-ipset  The file to output ipsets to\n"
-  printf -- "     --ipset-name    The name of the ipset\n"
-  printf -- "     --dest-ip       The destination IP to use\n"
+  printf -- "$(cat << EOF
+Options:
+   -h | --help     Display help
+   -v | --version  Display version
+   -r | --remove   Remove backups
+   -n | --noroot   Do not require root to output
+   -i | --ipset    Also download ipset sources
+   --output-hosts  The file to output hosts to
+   --output-ipset  The file to output ipsets to
+   --ipset-name    The name of the ipset
+   --dest-ip       The destination IP to use
+EOF
+)\n"
   return 0
 }
 
@@ -1210,7 +1277,8 @@ main_hosts()
 
   # Download
   action_msg "Downloading hosts_sources lists..."
-  download_sources "$(decide_dl_client)" "${HOSTS_SOURCES}" "process_hosts_sources" || cancel_sudoloop
+  download_sources "$(decide_dl_client)" \
+    "${HOSTS_SOURCES}" "process_hosts_sources" || cancel_sudoloop
 
   # Parse
   action_msg "Generating hosts file..."
@@ -1223,16 +1291,23 @@ main_hosts()
   # Install
   hosts=
   hosts="$(generate_new_hosts_file)" || cancel_sudoloop
-  main_hosts__file_backup="$(create_backup_name "${main_hosts__file}")"
-  backup_old_file "${main_hosts__sudo}" "${main_hosts__file}" "${main_hosts__file_backup}" || cancel_sudoloop
-  install_new_hosts_file "${main_hosts__sudo}" "${hosts}" "${main_hosts__file}" || cancel_sudoloop
-  fix_file_permissons "${main_hosts__sudo}" "${main_hosts__file}" || cancel_sudoloop
-  fix_file_permissons "${main_hosts__sudo}" "${main_hosts__file_backup}" || cancel_sudoloop
-  print_file_differences "${main_hosts__file}" "${main_hosts__file_backup}" || cancel_sudoloop
+  main_hosts__file_backup="$(create_backup_name \
+    "${main_hosts__file}")" || cancel_sudoloop
+  backup_old_file "${main_hosts__sudo}" \
+    "${main_hosts__file}" "${main_hosts__file_backup}" || cancel_sudoloop
+  install_new_hosts_file "${main_hosts__sudo}" \
+    "${hosts}" "${main_hosts__file}" || cancel_sudoloop
+  fix_file_permissons "${main_hosts__sudo}" \
+    "${main_hosts__file}" || cancel_sudoloop
+  fix_file_permissons "${main_hosts__sudo}" \
+    "${main_hosts__file_backup}" || cancel_sudoloop
+  print_file_differences "${main_hosts__file}" \
+    "${main_hosts__file_backup}" || cancel_sudoloop
 
   # Cleanup
   if [ "${main_hosts__remove_backup}" -eq 1 ]; then
-    remove_all_backup_files "${main_hosts__sudo}" "${main_hosts__file}" || cancel_sudoloop
+    remove_all_backup_files "${main_hosts__sudo}" \
+      "${main_hosts__file}" || cancel_sudoloop
   fi
 
   unset hosts
@@ -1260,11 +1335,13 @@ main_ipsets()
 
   # Begin
   printf -- "\n\n"
-  print_ipset_config "${main_ipsets__sudo}" "${main_ipsets__file}" "${main_ipsets__name}" || return 1
+  print_ipset_config "${main_ipsets__sudo}" \
+    "${main_ipsets__file}" "${main_ipsets__name}" || return 1
 
   # Download
   action_msg "Downloading ipset_sources lists..."
-  download_sources "$(decide_dl_client)" "${IPSET_SOURCES}" "process_ipset_sources" || cancel_sudoloop
+  download_sources "$(decide_dl_client)" \
+    "${IPSET_SOURCES}" "process_ipset_sources" || cancel_sudoloop
 
   # Parse
   action_msg "Generating ipset..."
@@ -1274,16 +1351,23 @@ main_ipsets()
   sort_entries || cancel_sudoloop
 
   # Install
-  main_ipsets__file_backup=$(create_backup_name "${main_ipsets__file}" ) || cancel_sudoloop
-  backup_old_file "${main_ipsets__sudo}" "${main_ipsets__file}" "${main_ipsets__file_backup}" || cancel_sudoloop
-  install_ipset_blocklist "${main_ipsets__sudo}" "${main_ipsets__file}" "${main_ipsets__name}" || cancel_sudoloop
-  fix_file_permissons "${main_ipsets__sudo}" "${main_ipsets__file}" || cancel_sudoloop
-  fix_file_permissons "${main_ipsets__sudo}" "${main_ipsets__file_backup}" || cancel_sudoloop
-  print_file_differences "${main_ipsets__file}" "${main_ipsets__file_backup}" || cancel_sudoloop
+  main_ipsets__file_backup=$(create_backup_name \
+    "${main_ipsets__file}" ) || cancel_sudoloop
+  backup_old_file "${main_ipsets__sudo}" \
+    "${main_ipsets__file}" "${main_ipsets__file_backup}" || cancel_sudoloop
+  install_ipset_blocklist "${main_ipsets__sudo}" \
+    "${main_ipsets__file}" "${main_ipsets__name}" || cancel_sudoloop
+  fix_file_permissons "${main_ipsets__sudo}" \
+    "${main_ipsets__file}" || cancel_sudoloop
+  fix_file_permissons "${main_ipsets__sudo}" \
+    "${main_ipsets__file_backup}" || cancel_sudoloop
+  print_file_differences "${main_ipsets__file}" \
+    "${main_ipsets__file_backup}" || cancel_sudoloop
 
   # Cleanup
   if [ "${main_ipsets__remove_backup}" -eq 1 ]; then
-    remove_all_backup_files "${main_ipsets__sudo}" "${main_ipsets__file}" || cancel_sudoloop
+    remove_all_backup_files "${main_ipsets__sudo}" \
+      "${main_ipsets__file}" || cancel_sudoloop
   fi
 
   unset main_ipsets__sudo
@@ -1423,7 +1507,8 @@ main()
           break
         fi
       else
-        # This is a plain arg and should be handled by one of the options which takes an argument
+        # This is a plain arg and should be handled by one of
+        # the options which takes an argument
         case "${long_option}" in
           output-hosts)
             dst_hosts="${optind_expanded}"
@@ -1482,7 +1567,8 @@ main()
   # Main process
 
   # Parse hosts files
-  main_hosts "${needs_sudo}" "${dst_hosts}" "${dst_ip}" "${remove_backups}" || cancel_sudoloop
+  main_hosts "${needs_sudo}" "${dst_hosts}" \
+    "${dst_ip}" "${remove_backups}" || cancel_sudoloop
 
   if [ "${manage_ipsets}" -eq 0 ]; then
     # End here
@@ -1493,7 +1579,8 @@ main()
   cleanup
 
   check_for_binary ipset || cancel_sudoloop
-  main_ipsets "${needs_sudo}" "${dst_ipset}" "${ipset_name}" "${remove_backups}" || cancel_sudoloop
+  main_ipsets "${needs_sudo}" "${dst_ipset}" \
+    "${ipset_name}" "${remove_backups}" || cancel_sudoloop
 
   # Finish
   cancel_sudoloop
